"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import {
  ArrowLeft,
  Bot,
  Clock3,
  MessageSquareText,
  Volume2,
} from "lucide-react";
import { ChatMessage } from "@/components/ChatMessage";
import { FeedbackPanel } from "@/components/FeedbackPanel";
import { LoadingDots } from "@/components/LoadingDots";
import { VoiceRecorder } from "@/components/VoiceRecorder";
import { useSpeechRecognition } from "@/hooks/useSpeechRecognition";
import type {
  ChatMessage as ChatMessageType,
  Correction,
  Scenario,
} from "@/lib/types";

type PracticeRoomProps = {
  scenario: Scenario;
};

function createMessage(role: "user" | "assistant", content: string) {
  return {
    id: `${role}-${Date.now()}-${Math.random().toString(16).slice(2)}`,
    role,
    content,
    createdAt: new Date().toISOString(),
  } satisfies ChatMessageType;
}

function createMockFeedback(text: string): Correction {
  return {
    original: text,
    corrected: text.trim().endsWith(".") ? text.trim() : `${text.trim()}.`,
    reason:
      "This is a UI preview. The real grammar reason will be generated by the correction API in a later step.",
    betterExpression:
      "I would like to explain my answer with a clear example and one specific detail.",
    scores: {
      grammar: 82,
      fluency: 80,
      vocabulary: 78,
      pronunciation: 81,
    },
  };
}

type ChatApiResponse = {
  reply?: string;
  error?: string;
};

export function PracticeRoom({ scenario }: PracticeRoomProps) {
  const openingMessage = useMemo(
    () => createMessage("assistant", scenario.openingQuestion),
    [scenario.openingQuestion],
  );
  const [messages, setMessages] = useState<ChatMessageType[]>([openingMessage]);
  const [isLoading, setIsLoading] = useState(false);
  const [isSpeaking, setIsSpeaking] = useState(false);
  const [currentFeedback, setCurrentFeedback] = useState<Correction>();
  const {
    transcript,
    isRecording,
    isSupported: isSpeechSupported,
    error: speechError,
    setTranscript,
    resetTranscript,
    startRecording,
    stopRecording,
  } = useSpeechRecognition({ lang: "en-US" });

  async function handleSend() {
    const text = transcript.trim();

    if (!text) {
      return;
    }

    stopRecording();

    const userMessage = createMessage("user", text);
    const nextMessages = [...messages, userMessage];

    setMessages(nextMessages);
    resetTranscript();
    setCurrentFeedback(createMockFeedback(text));
    setIsLoading(true);
    setIsSpeaking(false);

    try {
      const response = await fetch("/api/chat", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          scenario: scenario.id,
          messages: nextMessages,
        }),
      });
      const data = (await response.json()) as ChatApiResponse;
      const reply =
        data.reply ??
        "Good answer. Can you add one more detail to make it sound more natural?";

      setMessages((currentMessages) => [
        ...currentMessages,
        createMessage("assistant", reply),
      ]);
      setIsSpeaking(true);
    } catch {
      setMessages((currentMessages) => [
        ...currentMessages,
        createMessage(
          "assistant",
          "Good answer. Can you add one more detail to make it sound more natural?",
        ),
      ]);
      setIsSpeaking(true);
    } finally {
      setIsLoading(false);
      window.setTimeout(() => {
        setIsSpeaking(false);
      }, 2200);
    }
  }

  function handleEndPractice() {
    window.alert("Report generation will be connected in Step 8.");
  }

  return (
    <main className="flex min-h-screen flex-col bg-muted">
      <header className="border-b bg-background px-4 py-3">
        <div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-3">
          <div className="flex items-center gap-3">
            <Link
              className="inline-flex h-10 w-10 items-center justify-center rounded-lg border bg-card text-card-foreground transition hover:border-primary focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2"
              href="/scenarios"
              title="Back to scenarios"
            >
              <ArrowLeft className="h-4 w-4" aria-hidden="true" />
            </Link>
            <div>
              <p className="text-xs font-bold uppercase text-secondary">
                {scenario.difficulty} scenario
              </p>
              <h1 className="text-xl font-black sm:text-2xl">
                {scenario.title}
              </h1>
            </div>
          </div>

          <div className="flex flex-wrap gap-2 text-sm">
            <span className="inline-flex items-center gap-2 rounded-lg border bg-card px-3 py-2 font-semibold text-card-foreground">
              <Bot className="h-4 w-4 text-primary" aria-hidden="true" />
              {scenario.aiRole}
            </span>
            <span className="inline-flex items-center gap-2 rounded-lg border bg-card px-3 py-2 font-semibold text-card-foreground">
              <Clock3 className="h-4 w-4 text-secondary" aria-hidden="true" />
              00:00
            </span>
          </div>
        </div>
      </header>

      <div className="mx-auto grid w-full max-w-7xl flex-1 gap-4 px-4 py-4 lg:grid-cols-[minmax(0,1fr)_360px]">
        <section className="flex min-h-[560px] flex-col rounded-lg border bg-background shadow-sm">
          <div className="flex items-center justify-between gap-3 border-b px-5 py-4">
            <div>
              <h2 className="text-lg font-bold">Conversation</h2>
              <p className="text-sm text-muted-foreground">
                Answer in English. Keep each turn short and natural.
              </p>
            </div>
            <div className="flex items-center gap-2 rounded-lg bg-muted px-3 py-2 text-sm font-semibold text-muted-foreground">
              <MessageSquareText className="h-4 w-4" aria-hidden="true" />
              {messages.length} turns
            </div>
          </div>

          <div className="flex-1 space-y-4 overflow-y-auto px-5 py-5">
            {messages.map((message) => (
              <ChatMessage message={message} key={message.id} />
            ))}
            {isLoading ? (
              <div className="inline-flex items-center gap-3 rounded-lg border bg-card px-4 py-3 text-sm text-muted-foreground shadow-sm">
                <Bot className="h-4 w-4 text-primary" aria-hidden="true" />
                AI is thinking <LoadingDots />
              </div>
            ) : null}
            {isSpeaking ? (
              <div className="inline-flex items-center gap-3 rounded-lg border bg-card px-4 py-3 text-sm font-semibold text-secondary shadow-sm">
                <Volume2 className="h-4 w-4" aria-hidden="true" />
                AI is speaking
              </div>
            ) : null}
          </div>

          <div className="border-t p-4">
            <VoiceRecorder
              transcript={transcript}
              isRecording={isRecording}
              isSending={isLoading}
              isSpeechSupported={isSpeechSupported}
              speechError={speechError}
              onTranscriptChange={setTranscript}
              onStartRecording={startRecording}
              onStopRecording={stopRecording}
              onSend={handleSend}
              onEndPractice={handleEndPractice}
            />
          </div>
        </section>

        <FeedbackPanel feedback={currentFeedback} />
      </div>
    </main>
  );
}
