"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import {
  ArrowLeft,
  Bot,
  Clock3,
  MessageSquareText,
  Volume2,
} from "lucide-react";
import { ChatMessage } from "@/components/ChatMessage";
import { FeedbackPanel } from "@/components/FeedbackPanel";
import { StatusNotice } from "@/components/StatusNotice";
import { VoiceRecorder } from "@/components/VoiceRecorder";
import { useSpeechRecognition } from "@/hooks/useSpeechRecognition";
import type {
  ChatMessage as ChatMessageType,
  Correction,
  PracticeReport,
  Scenario,
} from "@/lib/types";

type PracticeRoomProps = {
  scenario: Scenario;
};

function createMessage(role: "user" | "assistant", content: string) {
  return {
    id: `${role}-${Date.now()}-${Math.random().toString(16).slice(2)}`,
    role,
    content,
    createdAt: new Date().toISOString(),
  } satisfies ChatMessageType;
}

function createMockFeedback(text: string): Correction {
  return {
    original: text,
    corrected: text.trim().endsWith(".") ? text.trim() : `${text.trim()}.`,
    reason:
      "This is a UI preview. The real grammar reason will be generated by the correction API in a later step.",
    betterExpression:
      "I would like to explain my answer with a clear example and one specific detail.",
    scores: {
      grammar: 82,
      fluency: 80,
      vocabulary: 78,
      pronunciation: 81,
    },
  };
}

type CorrectionApiResponse = Partial<Correction> & {
  error?: string;
};

type ReportApiResponse = Partial<PracticeReport> & {
  error?: string;
};

type SaveSessionApiResponse = {
  id?: string;
  provider?: "supabase" | "localStorage";
  error?: string;
};

type StreamChatResult = {
  reply: string;
  provider?: "deepseek" | "fallback";
  error?: string;
};

type CorrectionResult = {
  correction: Correction;
  usedFallback: boolean;
};

function parseSseBlock(block: string) {
  const lines = block.split(/\r?\n/);
  const dataLines: string[] = [];
  let event = "message";

  for (const line of lines) {
    if (line.startsWith("event:")) {
      event = line.slice("event:".length).trim();
    }

    if (line.startsWith("data:")) {
      dataLines.push(line.slice("data:".length).trimStart());
    }
  }

  if (dataLines.length === 0) {
    return { event, data: {} as Record<string, unknown> };
  }

  try {
    return {
      event,
      data: JSON.parse(dataLines.join("\n")) as Record<string, unknown>,
    };
  } catch {
    return { event, data: {} as Record<string, unknown> };
  }
}

async function streamChatReply({
  scenarioId,
  messages,
  onReply,
}: {
  scenarioId: string;
  messages: ChatMessageType[];
  onReply: (reply: string) => void;
}): Promise<StreamChatResult> {
  const response = await fetch("/api/chat/stream", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      scenario: scenarioId,
      messages,
    }),
  });

  if (!response.ok || !response.body) {
    throw new Error("Chat stream request failed.");
  }

  const reader = response.body.getReader();
  const decoder = new TextDecoder();
  let buffer = "";
  let reply = "";
  let provider: StreamChatResult["provider"];
  let streamError: string | undefined;

  function handleBlock(block: string) {
    const { event, data } = parseSseBlock(block);

    if (event === "token" && typeof data.token === "string") {
      reply += data.token;
      onReply(reply);
    }

    if (
      event === "done" &&
      (data.provider === "deepseek" || data.provider === "fallback")
    ) {
      provider = data.provider;
    }

    if (event === "error" && typeof data.message === "string") {
      streamError = data.message;
    }
  }

  while (true) {
    const { value, done } = await reader.read();

    if (done) {
      break;
    }

    buffer += decoder.decode(value, { stream: true });
    const blocks = buffer.split("\n\n");
    buffer = blocks.pop() ?? "";

    for (const block of blocks) {
      if (block.trim()) {
        handleBlock(block);
      }
    }
  }

  buffer += decoder.decode();

  if (buffer.trim()) {
    handleBlock(buffer);
  }

  if (!reply && streamError) {
    throw new Error(streamError);
  }

  return { reply, provider, error: streamError };
}

async function fetchCorrectionFeedback(
  scenarioId: string,
  text: string,
): Promise<CorrectionResult> {
  try {
    const response = await fetch("/api/correction", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        scenario: scenarioId,
        text,
      }),
    });
    const correctionData = (await response.json()) as CorrectionApiResponse;
    const correction =
      response.ok &&
      correctionData.original &&
      correctionData.corrected &&
      correctionData.reason &&
      correctionData.betterExpression &&
      correctionData.scores
        ? (correctionData as Correction)
        : createMockFeedback(text);

    return {
      correction,
      usedFallback: !response.ok || Boolean(correctionData.error),
    };
  } catch {
    return {
      correction: createMockFeedback(text),
      usedFallback: true,
    };
  }
}

export function PracticeRoom({ scenario }: PracticeRoomProps) {
  const router = useRouter();
  const openingMessage = useMemo(
    () => createMessage("assistant", scenario.openingQuestion),
    [scenario.openingQuestion],
  );
  const startedAt = useMemo(() => new Date(), []);
  const [messages, setMessages] = useState<ChatMessageType[]>([openingMessage]);
  const [corrections, setCorrections] = useState<Correction[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [isEnding, setIsEnding] = useState(false);
  const [isSpeaking, setIsSpeaking] = useState(false);
  const [statusMessage, setStatusMessage] = useState<string | null>(null);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [currentFeedback, setCurrentFeedback] = useState<Correction>();
  const {
    transcript,
    isRecording,
    isSupported: isSpeechSupported,
    error: speechError,
    setTranscript,
    resetTranscript,
    startRecording,
    stopRecording,
  } = useSpeechRecognition({ lang: "en-US" });

  async function handleSend() {
    const text = transcript.trim();

    if (!text) {
      return;
    }

    stopRecording();

    const userMessage = createMessage("user", text);
    const assistantMessage = createMessage("assistant", "");
    const nextMessages = [...messages, userMessage];

    setMessages([...nextMessages, assistantMessage]);
    resetTranscript();
    setCurrentFeedback(undefined);
    setIsLoading(true);
    setIsSpeaking(false);
    setStatusMessage(null);
    setErrorMessage(null);

    const correctionPromise = fetchCorrectionFeedback(scenario.id, text);

    try {
      const [chatResult, correctionResult] = await Promise.all([
        streamChatReply({
          scenarioId: scenario.id,
          messages: nextMessages,
          onReply: (reply) => {
            setMessages((currentMessages) =>
              currentMessages.map((message) =>
                message.id === assistantMessage.id
                  ? { ...message, content: reply }
                  : message,
              ),
            );
          },
        }),
        correctionPromise,
      ]);

      if (!chatResult.reply) {
        setMessages((currentMessages) =>
          currentMessages.map((message) =>
            message.id === assistantMessage.id
              ? {
                  ...message,
                  content:
                    "Good answer. Can you add one more detail to make it sound more natural?",
                }
              : message,
          ),
        );
      }

      setCurrentFeedback(correctionResult.correction);
      setCorrections((currentCorrections) => [
        ...currentCorrections,
        correctionResult.correction,
      ]);
      if (
        chatResult.provider === "fallback" ||
        chatResult.error ||
        correctionResult.usedFallback
      ) {
        setStatusMessage(
          "Some AI services used a fallback response, but your practice flow is still saved.",
        );
      }
      setIsSpeaking(true);
    } catch {
      const correctionResult = await correctionPromise;

      setMessages((currentMessages) =>
        currentMessages.map((message) =>
          message.id === assistantMessage.id
            ? {
                ...message,
                content:
                  "Good answer. Can you add one more detail to make it sound more natural?",
              }
            : message,
        ),
      );
      setCurrentFeedback(correctionResult.correction);
      setCorrections((currentCorrections) => [
        ...currentCorrections,
        correctionResult.correction,
      ]);
      setErrorMessage(
        "The AI service was unavailable, so TalkMate used a local fallback response.",
      );
      setIsSpeaking(true);
    } finally {
      setIsLoading(false);
      window.setTimeout(() => {
        setIsSpeaking(false);
      }, 2200);
    }
  }

  async function handleEndPractice() {
    if (isEnding) {
      return;
    }

    setIsEnding(true);
    setStatusMessage("Generating your learning report and saving this session.");
    setErrorMessage(null);

    try {
      const durationSeconds = Math.max(
        1,
        Math.round((Date.now() - startedAt.getTime()) / 1000),
      );
      const response = await fetch("/api/report", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          scenario: scenario.id,
          messages,
          corrections,
          durationSeconds,
        }),
      });
      const report = (await response.json()) as ReportApiResponse;
      const localSessionId = `local-${Date.now()}`;
      const endedAt = new Date();
      const localSession = {
        id: localSessionId,
        scenario: scenario.id,
        scenarioTitle: scenario.title,
        startedAt: startedAt.toISOString(),
        endedAt: endedAt.toISOString(),
        durationSeconds,
        messages,
        corrections,
        report,
      };

      window.localStorage.setItem(
        `talkmate-report-${localSessionId}`,
        JSON.stringify(localSession),
      );

      const saveResponse = await fetch("/api/sessions", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(localSession),
      });
      const savedSession = (await saveResponse.json()) as SaveSessionApiResponse;
      const sessionId = savedSession.id ?? localSessionId;

      if (savedSession.provider === "localStorage") {
        setStatusMessage(
          "Supabase is not configured, so this report is saved locally in your browser.",
        );
      }

      if (sessionId !== localSessionId) {
        window.localStorage.setItem(
          `talkmate-report-${sessionId}`,
          JSON.stringify({
            ...localSession,
            id: sessionId,
          }),
        );
      }

      router.push(`/report/${sessionId}`);
    } catch {
      setErrorMessage("Report generation failed. Please try again.");
      setStatusMessage(null);
      setIsEnding(false);
    }
  }

  return (
    <main className="flex min-h-screen flex-col bg-muted">
      <header className="border-b bg-background px-4 py-3">
        <div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-3">
          <div className="flex items-center gap-3">
            <Link
              className="inline-flex h-10 w-10 items-center justify-center rounded-lg border bg-card text-card-foreground transition hover:border-primary focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2"
              href="/scenarios"
              title="Back to scenarios"
            >
              <ArrowLeft className="h-4 w-4" aria-hidden="true" />
            </Link>
            <div>
              <p className="text-xs font-bold uppercase text-secondary">
                {scenario.difficulty} scenario
              </p>
              <h1 className="text-xl font-black sm:text-2xl">
                {scenario.title}
              </h1>
            </div>
          </div>

          <div className="flex flex-wrap gap-2 text-sm">
            <span className="inline-flex items-center gap-2 rounded-lg border bg-card px-3 py-2 font-semibold text-card-foreground">
              <Bot className="h-4 w-4 text-primary" aria-hidden="true" />
              {scenario.aiRole}
            </span>
            <span className="inline-flex items-center gap-2 rounded-lg border bg-card px-3 py-2 font-semibold text-card-foreground">
              <Clock3 className="h-4 w-4 text-secondary" aria-hidden="true" />
              00:00
            </span>
          </div>
        </div>
      </header>

      <div className="mx-auto grid w-full max-w-7xl flex-1 gap-4 px-4 py-4 lg:grid-cols-[minmax(0,1fr)_360px]">
        <section className="flex min-h-[560px] flex-col rounded-lg border bg-background shadow-sm">
          <div className="flex items-center justify-between gap-3 border-b px-5 py-4">
            <div>
              <h2 className="text-lg font-bold">Conversation</h2>
              <p className="text-sm text-muted-foreground">
                Answer in English. Keep each turn short and natural.
              </p>
            </div>
            <div className="flex items-center gap-2 rounded-lg bg-muted px-3 py-2 text-sm font-semibold text-muted-foreground">
              <MessageSquareText className="h-4 w-4" aria-hidden="true" />
              {messages.length} turns
            </div>
          </div>

          <div className="flex-1 space-y-4 overflow-y-auto px-5 py-5">
            {messages.map((message) => (
              <ChatMessage message={message} key={message.id} />
            ))}
            {isSpeaking ? (
              <div className="inline-flex items-center gap-3 rounded-lg border bg-card px-4 py-3 text-sm font-semibold text-secondary shadow-sm">
                <Volume2 className="h-4 w-4" aria-hidden="true" />
                AI is speaking
              </div>
            ) : null}
          </div>

          <div className="border-t p-4">
            <div className="mb-3 space-y-3">
              {isEnding ? (
                <StatusNotice
                  title="Preparing report"
                  description="Generating your learning report and saving the session."
                  tone="loading"
                />
              ) : null}
              {statusMessage && !isEnding ? (
                <StatusNotice
                  title="Practice flow continued"
                  description={statusMessage}
                  tone="info"
                />
              ) : null}
              {errorMessage ? (
                <StatusNotice
                  title="Fallback mode active"
                  description={errorMessage}
                  tone="warning"
                />
              ) : null}
            </div>
            <VoiceRecorder
              transcript={transcript}
              isRecording={isRecording}
              isSending={isLoading}
              isEnding={isEnding}
              isSpeechSupported={isSpeechSupported}
              speechError={speechError}
              onTranscriptChange={setTranscript}
              onStartRecording={startRecording}
              onStopRecording={stopRecording}
              onSend={handleSend}
              onEndPractice={handleEndPractice}
            />
          </div>
        </section>

        <FeedbackPanel feedback={currentFeedback} isLoading={isLoading} />
      </div>
    </main>
  );
}
